// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcFfeVSHJchwVN2AeIK3To1bThLp8mCOc',
    appId: '1:745618998004:web:b69f618c9edcc52dd9d4a1',
    messagingSenderId: '745618998004',
    projectId: 'clubapp-3a11a',
    authDomain: 'clubapp-3a11a.firebaseapp.com',
    storageBucket: 'clubapp-3a11a.appspot.com',
    measurementId: 'G-750EDEGFEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD82d_nFG4wlmYVzDYI995JZ18Pp8HeQzc',
    appId: '1:745618998004:android:13c089434e62bdc0d9d4a1',
    messagingSenderId: '745618998004',
    projectId: 'clubapp-3a11a',
    storageBucket: 'clubapp-3a11a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNGJWDsjLWSLC74ZEErsWf9m3k3mWgYl0',
    appId: '1:745618998004:ios:f0766a408056f12bd9d4a1',
    messagingSenderId: '745618998004',
    projectId: 'clubapp-3a11a',
    storageBucket: 'clubapp-3a11a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNGJWDsjLWSLC74ZEErsWf9m3k3mWgYl0',
    appId: '1:745618998004:ios:ae5947aec7118e1fd9d4a1',
    messagingSenderId: '745618998004',
    projectId: 'clubapp-3a11a',
    storageBucket: 'clubapp-3a11a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
